// flow-typed signature: 6b029f433ce236274e09f1dea951cd41
// flow-typed version: <<STUB>>/@attently/riek_v^2.0.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@attently/riek'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@attently/riek' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@attently/riek/lib/index' {
  declare module.exports: any;
}

declare module '@attently/riek/lib/RIEBase' {
  declare module.exports: any;
}

declare module '@attently/riek/lib/RIENumber' {
  declare module.exports: any;
}

declare module '@attently/riek/lib/RIESelect' {
  declare module.exports: any;
}

declare module '@attently/riek/lib/RIEStatefulBase' {
  declare module.exports: any;
}

declare module '@attently/riek/lib/RIETags' {
  declare module.exports: any;
}

declare module '@attently/riek/lib/RIETextArea' {
  declare module.exports: any;
}

declare module '@attently/riek/lib/RIEToggle' {
  declare module.exports: any;
}

declare module '@attently/riek/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@attently/riek/lib/index.js' {
  declare module.exports: $Exports<'@attently/riek/lib/index'>;
}
declare module '@attently/riek/lib/RIEBase.js' {
  declare module.exports: $Exports<'@attently/riek/lib/RIEBase'>;
}
declare module '@attently/riek/lib/RIENumber.js' {
  declare module.exports: $Exports<'@attently/riek/lib/RIENumber'>;
}
declare module '@attently/riek/lib/RIESelect.js' {
  declare module.exports: $Exports<'@attently/riek/lib/RIESelect'>;
}
declare module '@attently/riek/lib/RIEStatefulBase.js' {
  declare module.exports: $Exports<'@attently/riek/lib/RIEStatefulBase'>;
}
declare module '@attently/riek/lib/RIETags.js' {
  declare module.exports: $Exports<'@attently/riek/lib/RIETags'>;
}
declare module '@attently/riek/lib/RIETextArea.js' {
  declare module.exports: $Exports<'@attently/riek/lib/RIETextArea'>;
}
declare module '@attently/riek/lib/RIEToggle.js' {
  declare module.exports: $Exports<'@attently/riek/lib/RIEToggle'>;
}
declare module '@attently/riek/webpack.config.js' {
  declare module.exports: $Exports<'@attently/riek/webpack.config'>;
}
