// flow-typed signature: 57857094d103ce4229246bfc7e9e1f31
// flow-typed version: <<STUB>>/comma-separated-values_v^3.6.4/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'comma-separated-values'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'comma-separated-values' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'comma-separated-values/bench' {
  declare module.exports: any;
}

declare module 'comma-separated-values/csv' {
  declare module.exports: any;
}

declare module 'comma-separated-values/csv.min' {
  declare module.exports: any;
}

declare module 'comma-separated-values/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'comma-separated-values/bench.js' {
  declare module.exports: $Exports<'comma-separated-values/bench'>;
}
declare module 'comma-separated-values/csv.js' {
  declare module.exports: $Exports<'comma-separated-values/csv'>;
}
declare module 'comma-separated-values/csv.min.js' {
  declare module.exports: $Exports<'comma-separated-values/csv.min'>;
}
declare module 'comma-separated-values/test.js' {
  declare module.exports: $Exports<'comma-separated-values/test'>;
}
