// flow-typed signature: df9c733a8c764e64db58e4e5c03ceebf
// flow-typed version: <<STUB>>/eslint-plugin-chai-expect_v^1.1.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-chai-expect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-chai-expect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-chai-expect/lib/rules/missing-assertion' {
  declare module.exports: any;
}

declare module 'eslint-plugin-chai-expect/lib/rules/no-inner-compare' {
  declare module.exports: any;
}

declare module 'eslint-plugin-chai-expect/lib/rules/terminating-properties' {
  declare module.exports: any;
}

declare module 'eslint-plugin-chai-expect/lib/util/find-expect-call' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-chai-expect/index' {
  declare module.exports: $Exports<'eslint-plugin-chai-expect'>;
}
declare module 'eslint-plugin-chai-expect/index.js' {
  declare module.exports: $Exports<'eslint-plugin-chai-expect'>;
}
declare module 'eslint-plugin-chai-expect/lib/rules/missing-assertion.js' {
  declare module.exports: $Exports<'eslint-plugin-chai-expect/lib/rules/missing-assertion'>;
}
declare module 'eslint-plugin-chai-expect/lib/rules/no-inner-compare.js' {
  declare module.exports: $Exports<'eslint-plugin-chai-expect/lib/rules/no-inner-compare'>;
}
declare module 'eslint-plugin-chai-expect/lib/rules/terminating-properties.js' {
  declare module.exports: $Exports<'eslint-plugin-chai-expect/lib/rules/terminating-properties'>;
}
declare module 'eslint-plugin-chai-expect/lib/util/find-expect-call.js' {
  declare module.exports: $Exports<'eslint-plugin-chai-expect/lib/util/find-expect-call'>;
}
