// flow-typed signature: d0587109ee949945bb672e95ab8aa0f6
// flow-typed version: <<STUB>>/react-inline-edit_v^3.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-inline-edit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-inline-edit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-inline-edit/demo/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-inline-edit/demo/index' {
  declare module.exports: any;
}

declare module 'react-inline-edit/dist/InlineEdit' {
  declare module.exports: any;
}

declare module 'react-inline-edit/dist/utils/calcNodeHeight' {
  declare module.exports: any;
}

declare module 'react-inline-edit/scripts/InlineEdit' {
  declare module.exports: any;
}

declare module 'react-inline-edit/scripts/utils/calcNodeHeight' {
  declare module.exports: any;
}

declare module 'react-inline-edit/server' {
  declare module.exports: any;
}

declare module 'react-inline-edit/webpack.config.demo' {
  declare module.exports: any;
}

declare module 'react-inline-edit/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-inline-edit/demo/dist/bundle.js' {
  declare module.exports: $Exports<'react-inline-edit/demo/dist/bundle'>;
}
declare module 'react-inline-edit/demo/index.js' {
  declare module.exports: $Exports<'react-inline-edit/demo/index'>;
}
declare module 'react-inline-edit/dist/InlineEdit.js' {
  declare module.exports: $Exports<'react-inline-edit/dist/InlineEdit'>;
}
declare module 'react-inline-edit/dist/utils/calcNodeHeight.js' {
  declare module.exports: $Exports<'react-inline-edit/dist/utils/calcNodeHeight'>;
}
declare module 'react-inline-edit/scripts/InlineEdit.js' {
  declare module.exports: $Exports<'react-inline-edit/scripts/InlineEdit'>;
}
declare module 'react-inline-edit/scripts/utils/calcNodeHeight.js' {
  declare module.exports: $Exports<'react-inline-edit/scripts/utils/calcNodeHeight'>;
}
declare module 'react-inline-edit/server.js' {
  declare module.exports: $Exports<'react-inline-edit/server'>;
}
declare module 'react-inline-edit/webpack.config.demo.js' {
  declare module.exports: $Exports<'react-inline-edit/webpack.config.demo'>;
}
declare module 'react-inline-edit/webpack.config.js' {
  declare module.exports: $Exports<'react-inline-edit/webpack.config'>;
}
