// flow-typed signature: 1cdc3739174bea82a154d587afa6e96e
// flow-typed version: <<STUB>>/react-swipeable_v^4.3.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-swipeable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-swipeable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-swipeable/lib/__mocks__/react' {
  declare module.exports: any;
}

declare module 'react-swipeable/lib/Swipeable' {
  declare module.exports: any;
}

declare module 'react-swipeable/src/__mocks__/react' {
  declare module.exports: any;
}

declare module 'react-swipeable/src/__tests__/helpers/events' {
  declare module.exports: any;
}

declare module 'react-swipeable/src/__tests__/Swipeable.spec' {
  declare module.exports: any;
}

declare module 'react-swipeable/src/Swipeable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-swipeable/lib/__mocks__/react.js' {
  declare module.exports: $Exports<'react-swipeable/lib/__mocks__/react'>;
}
declare module 'react-swipeable/lib/Swipeable.js' {
  declare module.exports: $Exports<'react-swipeable/lib/Swipeable'>;
}
declare module 'react-swipeable/src/__mocks__/react.js' {
  declare module.exports: $Exports<'react-swipeable/src/__mocks__/react'>;
}
declare module 'react-swipeable/src/__tests__/helpers/events.js' {
  declare module.exports: $Exports<'react-swipeable/src/__tests__/helpers/events'>;
}
declare module 'react-swipeable/src/__tests__/Swipeable.spec.js' {
  declare module.exports: $Exports<'react-swipeable/src/__tests__/Swipeable.spec'>;
}
declare module 'react-swipeable/src/Swipeable.js' {
  declare module.exports: $Exports<'react-swipeable/src/Swipeable'>;
}
