// flow-typed signature: 5b7185651f72726490f3867dcca9039b
// flow-typed version: <<STUB>>/react-keybinding-component_v^0.5.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-keybinding-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-keybinding-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-keybinding-component/dist/react-keybinding-component' {
  declare module.exports: any;
}

declare module 'react-keybinding-component/gulpfile' {
  declare module.exports: any;
}

declare module 'react-keybinding-component/js/react-keybinding-component' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-keybinding-component/dist/react-keybinding-component.js' {
  declare module.exports: $Exports<'react-keybinding-component/dist/react-keybinding-component'>;
}
declare module 'react-keybinding-component/gulpfile.js' {
  declare module.exports: $Exports<'react-keybinding-component/gulpfile'>;
}
declare module 'react-keybinding-component/js/react-keybinding-component.jsx' {
  declare module.exports: $Exports<'react-keybinding-component/js/react-keybinding-component'>;
}
